#if !canImport(ObjectiveC)
import XCTest

extension ImagesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImagesTests = [
        ("testNoImage", testNoImage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ImagesTests.__allTests__ImagesTests),
    ]
}
#endif
